name: Node CI
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies and Build
      run: |
        npm i yarn -g
        yarn
        yarn run build
      env:
        CI: true

    - name: Test with Coverage Output
      run: |
        yarn run test --silent --coverage --json

    - name: Send Coverage Reports to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/*.json

